<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>School_Fees_Management_System</RootNamespace>
    <StartupObject>School_Fees_Management_System.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="core\images\Giffy.gif" />
    <None Remove="core\images\login.gif" />
    <None Remove="core\images\loginGif.gif" />
    <None Remove="core\images\loginGiffy.gif" />
    <None Remove="core\images\Sucessful_Gif.gif" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="core\images\Giffy.gif" />
    <EmbeddedResource Include="core\images\loginGiffy.gif" />
    <EmbeddedResource Include="core\images\Sucessful_Gif.gif" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.9.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.33" />
    <PackageReference Include="System.Data.OleDb" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
    <Compile Update="My Project\Resources.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="dsDummySchema.xsd">
      <Generator></Generator>
    </None>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="Reports\FinancialReport.rdlc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="My Project\Resources.resx">
      <CustomToolNamespace>My.Resources</CustomToolNamespace>
      <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.vb</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>